// <auto-generated />
using EBroker.Management.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Diagnostics.CodeAnalysis;

namespace ebroker_management_data.Migrations
{
    [ExcludeFromCodeCoverage]
    [DbContext(typeof(EBrokerDbContext))]
    partial class EBrokerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("EBroker.Management.Domain.Equity.Equity", b =>
                {
                    b.Property<string>("EquityId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EquityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EquityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("EquityId")
                        .HasName("PK_Equity");

                    b.ToTable("Equity");
                });

            modelBuilder.Entity("EBroker.Management.Domain.Trading.TraderEquity", b =>
                {
                    b.Property<string>("TraderEquityId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EquityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("TraderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TraderEquityId")
                        .HasName("PK_TraderEquity");

                    b.ToTable("TraderEquity");
                });

            modelBuilder.Entity("EBroker.Management.Domain.Trading.TraderProfile", b =>
                {
                    b.Property<string>("TraderId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Funds")
                        .HasColumnType("double");

                    b.Property<string>("TraderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TraderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TraderId")
                        .HasName("PK_Trader");

                    b.ToTable("Trader");
                });
#pragma warning restore 612, 618
        }
    }
}
